### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by TemSanych** [xsolla/xsolla-sdk-php#16]
Hello! I need help with integration xsolla-sdk-php, as I can not understand how can I install the mobile payments to your online project.

**Comment by zakharovvi** [comment]
Hello @TemSanych 

Please follow the integration guides in our documentation http://developers.xsolla.com/
Also you can email our integration team at integration@xsolla.com for assistance.

**Comment by TemSanych** [comment]
А по русски не общаетесь?
