### ISSUE TITLE
Guzzle 3 has been deprecated

### ISSUE THREAD

**Issue by Lidbetter** [xsolla/xsolla-sdk-php#42]
[guzzle3](https://github.com/guzzle/guzzle3) has been deprecated since the start of 2015, are there any plans to release a new version of the SDK with updated dependencies?

In it's current state we cannot use the sdk in a production environment.

**Comment by valetanddama** [comment]
@Lidbetter what error did you get?

**Comment by Lidbetter** [comment]
There are no crashing errors.

We cannot add new 3rd party dependencies to our project which are already deprecated and abandoned by the maintainer. The general policy we have in place is to help reduce risk and minimize potential issues regarding security.

Is there an eta for this to be addressed and fixed?

**Comment by valetanddama** [comment]
we'll update guzzle at this week

**Comment by valetanddama** [comment]
You can use:
1.  xsolla-sdk-php ~3.3 with guzzle ~5.3
2. xsolla-sdk-php ~4.0 with guzzle ~6.0
