### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by nanaya** [xsolla/xsolla-sdk-php#74]
There's currently a version requirement of `<7.3`. I tried the package with 7.3 and it seems to work fine in my (basic) test.

**Comment by andkab** [comment]
+

**Comment by thiefccc** [comment]
The PHP version has been increased.

**Comment by nanaya** [comment]
Looks like it's not published in packagist yet.

https://packagist.org/packages/xsolla/xsolla-sdk-php

**Comment by nanaya** [comment]
Also it doesn't install on latest php

```
xsolla/xsolla-sdk-php v4.1.0 requires php >=7.1.3 <=7.3 -> your PHP version (7.3.12) does not satisfy that requirement.
```
